"""The reversal anagram sampler for AudioLDM 2.

The same construction as `ava.audio.engine` -- at every step the noise
estimate is the average of the forward branch and the time-flipped branch,

    eps = 0.5 * (eps(z, p_forward) + flip(eps(flip(z), p_reverse)))

-- on a different latent. AudioLDM 2 denoises a mel spectrogram's latent of
shape (B, 8, T/4, 16), so time is the second-to-last axis and the flip is
`flip_window(..., dim=-2)`; the arithmetic is shared with the Stable Audio
engine and tested there.

What differs from Stable Audio, and why it matters here:

**The latent is sized to the request.** AudioLDM 2 makes a latent of
`duration / 40 ms` frames rather than always 1024, so the flip covers the
whole latent and nothing has to be left alone. The request is rounded *up* to
the 40 ms grid and the whole decoded span is returned, rather than cropping
the tail as the pipeline does: with a crop, the reverse branch's sound would
start up to 30 ms late.

**Reversal is exact in the mel domain.** The waveform is synthesised from the
mel spectrogram by HiFi-GAN, which invents the phase and knows nothing about
time direction, so the only part of the model that can fail to commute with
the flip is the 2D VAE (measured by Step 0b with `--codec audioldm2`).

**Conditioning is three tensors, not one.** The UNet cross-attends to a T5
sequence with a mask and to eight hidden states generated by GPT-2 from the
projected CLAP and T5 embeddings. `encode_prompt` produces all three, and is
deterministic (greedy hidden states, no sampling), so a seed still fixes the
sample. All three are laid out as [uncond, forward, uncond, reverse].
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np
import torch

from ava.audio.engine import anagram_epsilon, flip_window
from ava.audio.mel import AUDIOLDM2_MEL, MelConfig, mel_frames
from ava.audio.spec import AudioCandidateSpec

MODEL_ID = "cvssp/audioldm2"
# Time is the second-to-last axis of (B, C, T, mel).
TIME_DIM = -2


def stack_padded(rows: list[torch.Tensor]) -> torch.Tensor:
    """Concatenate (1, L_i, ...) rows along the batch, zero-padding L to the longest.

    The T5 tokenizer does not pad to a fixed length, so a prompt's sequence is
    as long as its tokens and two prompts rarely agree. Padding with zeros is
    what a padded tokenisation would amount to once the attention mask -- which
    is padded the same way, with zeros -- hides those positions from the UNet's
    cross-attention. Pure, so it is tested on hand-written tensors.
    """
    longest = max(row.shape[1] for row in rows)
    padded = []
    for row in rows:
        pad = longest - row.shape[1]
        if pad:
            filler = row.new_zeros((row.shape[0], pad) + tuple(row.shape[2:]))
            row = torch.cat([row, filler], dim=1)
        padded.append(row)
    return torch.cat(padded, dim=0)


class AudioLDM2Engine:
    """Holds the AudioLDM 2 pipeline and samples one anagram at a time.

    Same shape as `AudioAnagramEngine`: the pipeline stays resident, prompt
    embeddings are cached per string, and `generate` returns (channels, n)
    float audio -- here (1, n) at 16 kHz, since the model is mono.
    """

    def __init__(
        self,
        model_id: str = MODEL_ID,
        device: str = "cuda",
        dtype: torch.dtype = torch.float16,
        mel: MelConfig = AUDIOLDM2_MEL,
    ) -> None:
        self.model_id = model_id
        self.device = device
        self.torch_device = torch.device(device)
        self.dtype = dtype
        self.mel = mel
        self._pipe: Any = None
        self._embed_cache: dict[
            str, tuple[torch.Tensor, torch.Tensor, torch.Tensor]
        ] = {}

    # ---- lazy loading -----------------------------------------------------

    @property
    def pipe(self) -> Any:
        if self._pipe is None:
            from diffusers import AudioLDM2Pipeline

            pipe = AudioLDM2Pipeline.from_pretrained(
                self.model_id, torch_dtype=self.dtype
            )
            self._pipe = pipe.to(self.device)
            if int(self._pipe.vocoder.config.sampling_rate) != self.mel.sample_rate:
                raise ValueError(
                    f"{self.model_id} runs at {self._pipe.vocoder.config.sampling_rate}"
                    f" Hz, the front end at {self.mel.sample_rate} Hz"
                )
            if int(self._pipe.vae_scale_factor) != self.mel.latent_stride:
                raise ValueError(
                    f"{self.model_id} downsamples time by"
                    f" {self._pipe.vae_scale_factor}, the front end assumes"
                    f" {self.mel.latent_stride}"
                )
        return self._pipe

    @property
    def sample_rate(self) -> int:
        return int(self.pipe.vocoder.config.sampling_rate)

    def latent_frames(self, duration_s: float) -> int:
        """How many latent frames a duration occupies, rounded up to the grid.

        Pure arithmetic on the front end's constants (10 ms per mel frame,
        four mel frames per latent frame), so it is testable without a model.
        """
        samples = int(math.ceil(duration_s * self.mel.sample_rate))
        return mel_frames(samples, self.mel) // self.mel.latent_stride

    def effective_duration_s(self, duration_s: float) -> float:
        """The duration actually generated: `duration_s` rounded up to 40 ms."""
        frames = self.latent_frames(duration_s)
        return frames * self.mel.samples_per_latent_frame / self.mel.sample_rate

    # ---- conditioning -----------------------------------------------------

    @torch.no_grad()
    def _prompt_emb(
        self, prompt: str
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """(T5 sequence, its mask, GPT-2 generated states) for one prompt."""
        if prompt not in self._embed_cache:
            embeds, mask, generated = self.pipe.encode_prompt(
                prompt, self.device, 1, False
            )
            self._embed_cache[prompt] = (embeds, mask, generated)
        return self._embed_cache[prompt]

    @torch.no_grad()
    def _conditioning(
        self, spec: AudioCandidateSpec
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """The three conditioning tensors, rows [uncond, forward, uncond, reverse].

        The unconditional row is the negative prompt encoded like any other
        text, which is what the pipeline does too (an empty string when none
        is given). The T5 rows are padded to the longest of the four, mask
        included; the GPT-2 rows are always eight states long.
        """
        forward = self._prompt_emb(spec.prompt_forward)
        reverse = self._prompt_emb(spec.prompt_reverse)
        uncond = self._prompt_emb(spec.negative_prompt)
        rows = [uncond, forward, uncond, reverse]
        embeds = stack_padded([row[0] for row in rows])
        mask = stack_padded([row[1] for row in rows])
        generated = stack_padded([row[2] for row in rows])
        return embeds, mask, generated

    # ---- sampling ---------------------------------------------------------

    @torch.no_grad()
    def generate(self, spec: AudioCandidateSpec) -> np.ndarray:
        """Sample one anagram. Returns (1, n) float at 16 kHz.

        `n` covers `effective_duration_s(spec.duration_s)`, not the requested
        duration, for the reason given in the module docstring.
        """
        pipe = self.pipe
        embeds, mask, generated = self._conditioning(spec)
        frames = self.latent_frames(spec.duration_s)

        pipe.scheduler.set_timesteps(spec.num_inference_steps, device=self.device)
        timesteps = pipe.scheduler.timesteps

        generator = torch.Generator(self.device).manual_seed(spec.seed)
        latents = pipe.prepare_latents(
            1,
            int(pipe.unet.config.in_channels),
            frames * self.mel.latent_stride,
            embeds.dtype,
            self.torch_device,
            generator,
        )

        for t in timesteps:
            flipped = flip_window(latents, frames, TIME_DIM)
            model_input = torch.cat([latents, latents, flipped, flipped])
            model_input = pipe.scheduler.scale_model_input(model_input, t)

            prediction = pipe.unet(
                model_input,
                t,
                encoder_hidden_states=generated,
                encoder_hidden_states_1=embeds,
                encoder_attention_mask_1=mask,
                return_dict=False,
            )[0]

            eps = anagram_epsilon(prediction, spec.guidance_scale, frames, TIME_DIM)
            latents = pipe.scheduler.step(eps, t, latents).prev_sample

        mel = pipe.vae.decode(latents / pipe.vae.config.scaling_factor).sample
        audio = pipe.mel_spectrogram_to_waveform(mel)
        return audio.numpy().reshape(1, -1)
