"""Illusion samplers for AudioLDM 2: the reversal anagram and the frequency hybrid.

Both run the same loop -- one batch of four rows per step, conditioned as
[uncond, slot 0, uncond, slot 1], guidance applied within each branch -- and
differ only in what goes into the batch and how the two branches' noise
estimates are combined:

    reversal   eps = 0.5 * (eps(z, p_0) + flip(eps(flip(z), p_1)))    Visual Anagrams
    hybrid     eps = high(eps(z, p_0)) + low(eps(z, p_1))              Factorized Diff.

The reversal is Visual Anagrams' construction with time reversal as the view;
the hybrid is Factorized Diffusion's with a low-pass in place of the blur,
where `low` is the fitted projector of `ava.audio.bands` and `high` its
complement, so the two components sum to the whole estimate.

The latent is a mel spectrogram's, (B, 8, T/4, 16): time is the second-to-last
axis (`TIME_DIM`), and the arithmetic of the reversal is shared with the
Stable Audio engine and tested there.

What differs from Stable Audio, and why it matters here:

**The latent is sized to the request.** AudioLDM 2 makes a latent of
`duration / 40 ms` frames rather than always 1024, so the flip covers the
whole latent and nothing has to be left alone. The request is rounded *up* to
the 40 ms grid and the whole decoded span is returned, rather than cropping
the tail as the pipeline does: with a crop, the reverse branch's sound would
start up to 30 ms late.

**Reversal is exact in the mel domain.** The waveform is synthesised from the
mel spectrogram by HiFi-GAN, which invents the phase and knows nothing about
time direction, so the only part of the model that can fail to commute with
the flip is the 2D VAE (measured by Step 0b with `--codec audioldm2`).

**Conditioning is three tensors, not one.** The UNet cross-attends to a T5
sequence with a mask and to eight hidden states generated by GPT-2 from the
projected CLAP and T5 embeddings. `encode_prompt` produces all three, and is
deterministic (greedy hidden states, no sampling), so a seed still fixes the
sample. The T5 rows are padded to the longest of the four, mask included.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np
import torch

from ava.audio.bands import LowpassProjector
from ava.audio.engine import anagram_epsilon, flip_window
from ava.audio.mel import AUDIOLDM2_MEL, MelConfig, mel_frames
from ava.audio.spec import AudioCandidateSpec

MODEL_ID = "cvssp/audioldm2"
# Time is the second-to-last axis of (B, C, T, mel).
TIME_DIM = -2


def stack_padded(rows: list[torch.Tensor]) -> torch.Tensor:
    """Concatenate (1, L_i, ...) rows along the batch, zero-padding L to the longest.

    The T5 tokenizer does not pad to a fixed length, so a prompt's sequence is
    as long as its tokens and two prompts rarely agree. Padding with zeros is
    what a padded tokenisation would amount to once the attention mask -- which
    is padded the same way, with zeros -- hides those positions from the UNet's
    cross-attention. Pure, so it is tested on hand-written tensors.
    """
    longest = max(row.shape[1] for row in rows)
    padded = []
    for row in rows:
        pad = longest - row.shape[1]
        if pad:
            filler = row.new_zeros((row.shape[0], pad) + tuple(row.shape[2:]))
            row = torch.cat([row, filler], dim=1)
        padded.append(row)
    return torch.cat(padded, dim=0)


def hybrid_epsilon(
    prediction: torch.Tensor, guidance_scale: float, projector: LowpassProjector
) -> torch.Tensor:
    """Fold the batch-of-4 output into one epsilon, Factorized Diffusion style.

    Rows arrive as [uncond, near, uncond, far]. Guidance is applied within
    each branch; then the near branch supplies the high-band component and
    the far branch the low-band one, and the two are summed. Because the
    projector's components sum to the identity, two branches that agree
    return their common estimate unchanged.
    """
    uncond_n, cond_n, uncond_f, cond_f = prediction.chunk(4)
    eps_near = uncond_n + guidance_scale * (cond_n - uncond_n)
    eps_far = uncond_f + guidance_scale * (cond_f - uncond_f)
    _, high_of_near = projector.split_epsilon(eps_near)
    low_of_far, _ = projector.split_epsilon(eps_far)
    return high_of_near + low_of_far


class _AudioLDM2Sampler:
    """Holds the AudioLDM 2 pipeline; subclasses say how the two branches meet.

    Same shape as `AudioAnagramEngine`: the pipeline stays resident, prompt
    embeddings are cached per string, and `generate` returns (channels, n)
    float audio -- here (1, n) at 16 kHz, since the model is mono.
    """

    def __init__(
        self,
        model_id: str = MODEL_ID,
        device: str = "cuda",
        dtype: torch.dtype = torch.float16,
        mel: MelConfig = AUDIOLDM2_MEL,
    ) -> None:
        self.model_id = model_id
        self.device = device
        self.torch_device = torch.device(device)
        self.dtype = dtype
        self.mel = mel
        self._pipe: Any = None
        self._embed_cache: dict[
            str, tuple[torch.Tensor, torch.Tensor, torch.Tensor]
        ] = {}

    # ---- lazy loading -----------------------------------------------------

    @property
    def pipe(self) -> Any:
        if self._pipe is None:
            from diffusers import AudioLDM2Pipeline

            pipe = AudioLDM2Pipeline.from_pretrained(
                self.model_id, torch_dtype=self.dtype
            )
            self._pipe = pipe.to(self.device)
            if int(self._pipe.vocoder.config.sampling_rate) != self.mel.sample_rate:
                raise ValueError(
                    f"{self.model_id} runs at {self._pipe.vocoder.config.sampling_rate}"
                    f" Hz, the front end at {self.mel.sample_rate} Hz"
                )
            if int(self._pipe.vae_scale_factor) != self.mel.latent_stride:
                raise ValueError(
                    f"{self.model_id} downsamples time by"
                    f" {self._pipe.vae_scale_factor}, the front end assumes"
                    f" {self.mel.latent_stride}"
                )
        return self._pipe

    @property
    def sample_rate(self) -> int:
        return int(self.pipe.vocoder.config.sampling_rate)

    def latent_frames(self, duration_s: float) -> int:
        """How many latent frames a duration occupies, rounded up to the grid.

        Pure arithmetic on the front end's constants (10 ms per mel frame,
        four mel frames per latent frame), so it is testable without a model.
        """
        samples = int(math.ceil(duration_s * self.mel.sample_rate))
        return mel_frames(samples, self.mel) // self.mel.latent_stride

    def effective_duration_s(self, duration_s: float) -> float:
        """The duration actually generated: `duration_s` rounded up to 40 ms."""
        frames = self.latent_frames(duration_s)
        return frames * self.mel.samples_per_latent_frame / self.mel.sample_rate

    # ---- conditioning -----------------------------------------------------

    @torch.no_grad()
    def _prompt_emb(
        self, prompt: str
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """(T5 sequence, its mask, GPT-2 generated states) for one prompt."""
        if prompt not in self._embed_cache:
            embeds, mask, generated = self.pipe.encode_prompt(
                prompt, self.device, 1, False
            )
            self._embed_cache[prompt] = (embeds, mask, generated)
        return self._embed_cache[prompt]

    @torch.no_grad()
    def _conditioning(
        self, spec: AudioCandidateSpec
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """The three conditioning tensors, rows [uncond, slot 0, uncond, slot 1].

        The unconditional row is the negative prompt encoded like any other
        text, which is what the pipeline does too (an empty string when none
        is given).
        """
        first = self._prompt_emb(spec.prompt_forward)
        second = self._prompt_emb(spec.prompt_reverse)
        uncond = self._prompt_emb(spec.negative_prompt)
        rows = [uncond, first, uncond, second]
        embeds = stack_padded([row[0] for row in rows])
        mask = stack_padded([row[1] for row in rows])
        generated = stack_padded([row[2] for row in rows])
        return embeds, mask, generated

    # ---- the two branches: what goes in, how they meet --------------------

    def _branch_input(self, latents: torch.Tensor, frames: int) -> torch.Tensor:
        raise NotImplementedError

    def _combine(
        self, prediction: torch.Tensor, guidance_scale: float, frames: int
    ) -> torch.Tensor:
        raise NotImplementedError

    # ---- sampling ---------------------------------------------------------

    @torch.no_grad()
    def generate(self, spec: AudioCandidateSpec) -> np.ndarray:
        """Sample one candidate. Returns (1, n) float at 16 kHz.

        `n` covers `effective_duration_s(spec.duration_s)`, not the requested
        duration, for the reason given in the module docstring.
        """
        pipe = self.pipe
        embeds, mask, generated = self._conditioning(spec)
        frames = self.latent_frames(spec.duration_s)

        pipe.scheduler.set_timesteps(spec.num_inference_steps, device=self.device)
        timesteps = pipe.scheduler.timesteps

        generator = torch.Generator(self.device).manual_seed(spec.seed)
        latents = pipe.prepare_latents(
            1,
            int(pipe.unet.config.in_channels),
            frames * self.mel.latent_stride,
            embeds.dtype,
            self.torch_device,
            generator,
        )

        for t in timesteps:
            model_input = self._branch_input(latents, frames)
            model_input = pipe.scheduler.scale_model_input(model_input, t)

            prediction = pipe.unet(
                model_input,
                t,
                encoder_hidden_states=generated,
                encoder_hidden_states_1=embeds,
                encoder_attention_mask_1=mask,
                return_dict=False,
            )[0]

            eps = self._combine(prediction, spec.guidance_scale, frames)
            latents = pipe.scheduler.step(eps, t, latents).prev_sample

        mel = pipe.vae.decode(latents / pipe.vae.config.scaling_factor).sample
        audio = pipe.mel_spectrogram_to_waveform(mel)
        return audio.numpy().reshape(1, -1)


class AudioLDM2Engine(_AudioLDM2Sampler):
    """The reversal anagram: slot 0 is heard forwards, slot 1 backwards."""

    def _branch_input(self, latents: torch.Tensor, frames: int) -> torch.Tensor:
        flipped = flip_window(latents, frames, TIME_DIM)
        return torch.cat([latents, latents, flipped, flipped])

    def _combine(
        self, prediction: torch.Tensor, guidance_scale: float, frames: int
    ) -> torch.Tensor:
        return anagram_epsilon(prediction, guidance_scale, frames, TIME_DIM)


class AudioLDM2HybridEngine(_AudioLDM2Sampler):
    """The frequency hybrid: slot 0 is heard in the room, slot 1 through a wall.

    Both branches see the same latent; the projector decides which part of
    each branch's estimate is kept. The projector is a fitted artefact
    (Step 0c) and must be given: there is no default.
    """

    def __init__(self, projector: LowpassProjector, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.projector = projector

    def _branch_input(self, latents: torch.Tensor, frames: int) -> torch.Tensor:
        return torch.cat([latents] * 4)

    def _combine(
        self, prediction: torch.Tensor, guidance_scale: float, frames: int
    ) -> torch.Tensor:
        return hybrid_epsilon(prediction, guidance_scale, self.projector)
